-- Turni / Shift Planner foundation.
--
-- This migration is deliberately additive: it creates the canonical,
-- property-scoped data model and its authorization boundary without moving
-- any data from the legacy Plannerturni project and without enabling the
-- module for any property. Module entitlement remains an explicit later
-- release step.

-- ---------------------------------------------------------------------------
-- Permissions
-- ---------------------------------------------------------------------------

insert into permissions (slug, module_id)
select permission_slug, m.id
from modules m
cross join (values
  ('shifts.view'),
  ('shifts.manage'),
  ('shifts.requests.manage')
) as wanted(permission_slug)
where m.slug = 'shifts'
on conflict (slug) do update set module_id = excluded.module_id;

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join (values
  ('organization_admin', 'shifts.view'),
  ('organization_admin', 'shifts.manage'),
  ('organization_admin', 'shifts.requests.manage'),
  ('property_admin', 'shifts.view'),
  ('property_admin', 'shifts.manage'),
  ('property_admin', 'shifts.requests.manage'),
  ('manager', 'shifts.view'),
  ('manager', 'shifts.manage'),
  ('manager', 'shifts.requests.manage'),
  ('receptionist', 'shifts.view')
) as wanted(role_slug, permission_slug) on wanted.role_slug = r.slug
join permissions p on p.slug = wanted.permission_slug
on conflict (role_id, permission_id) do nothing;

-- ---------------------------------------------------------------------------
-- Canonical property-scoped schema
-- ---------------------------------------------------------------------------

create table shift_staff_profiles (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references properties(id) on delete restrict,
  profile_id uuid not null references profiles(id) on delete restrict,
  employee_type text not null default 'day'
    check (employee_type in ('day', 'rotating', 'night', 'director', 'front_office_manager')),
  rest_type text not null default 'rotating'
    check (rest_type in ('rotating', 'fixed')),
  fixed_rest_day smallint check (fixed_rest_day between 0 and 6),
  rotation_slot smallint,
  active boolean not null default true,
  color text,
  extra_shift_codes text[] not null default '{}',
  annual_leave_quota numeric(6,2) not null default 26 check (annual_leave_quota >= 0),
  annual_permission_hours numeric(7,2) not null default 88 check (annual_permission_hours >= 0),
  team_member boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id, profile_id),
  unique (property_id, id),
  check ((rest_type = 'fixed' and fixed_rest_day is not null) or rest_type = 'rotating')
);

create table shifts (
  id bigint generated by default as identity primary key,
  property_id uuid not null references properties(id) on delete restrict,
  staff_profile_id uuid not null,
  shift_date date not null,
  code text not null check (btrim(code) <> ''),
  do_not_move boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id, staff_profile_id, shift_date),
  foreign key (property_id, staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create table shift_swap_requests (
  id bigint generated by default as identity primary key,
  property_id uuid not null references properties(id) on delete restrict,
  requester_staff_profile_id uuid not null,
  recipient_staff_profile_id uuid not null,
  requester_date date not null,
  recipient_date date not null,
  requester_shift_code text not null check (btrim(requester_shift_code) <> ''),
  recipient_shift_code text not null check (btrim(recipient_shift_code) <> ''),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  system_note text,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_staff_profile_id <> recipient_staff_profile_id),
  foreign key (property_id, requester_staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict,
  foreign key (property_id, recipient_staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create table shift_absence_requests (
  id bigint generated by default as identity primary key,
  property_id uuid not null references properties(id) on delete restrict,
  staff_profile_id uuid not null,
  starts_on date not null,
  ends_on date not null,
  absence_type text not null check (absence_type in ('leave', 'permission')),
  affected_shift_code text,
  note text,
  hours numeric(6,2) check (hours is null or hours > 0),
  starts_at time,
  ends_at time,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  foreign key (property_id, staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create table shift_preassignment_requests (
  id bigint generated by default as identity primary key,
  property_id uuid not null references properties(id) on delete restrict,
  staff_profile_id uuid not null,
  starts_on date not null,
  ends_on date not null,
  requested_shift_code text not null check (btrim(requested_shift_code) <> ''),
  note text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  foreign key (property_id, staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create table shift_month_states (
  property_id uuid not null references properties(id) on delete restrict,
  month_start date not null check (month_start = date_trunc('month', month_start)::date),
  status text not null default 'draft' check (status in ('draft', 'final')),
  updated_at timestamptz not null default now(),
  primary key (property_id, month_start)
);

create table shift_settings (
  property_id uuid not null references properties(id) on delete restrict,
  key text not null check (btrim(key) <> ''),
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (property_id, key)
);

create table shift_preferences (
  property_id uuid not null references properties(id) on delete restrict,
  staff_profile_id uuid not null,
  preferred_shift_codes text[] not null default '{}',
  avoid_uncomfortable_sequences boolean not null default false,
  day_preferences jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (property_id, staff_profile_id),
  foreign key (property_id, staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create table shift_read_notifications (
  property_id uuid not null references properties(id) on delete restrict,
  staff_profile_id uuid not null,
  notification_key text not null check (btrim(notification_key) <> ''),
  read_at timestamptz not null default now(),
  primary key (property_id, staff_profile_id, notification_key),
  foreign key (property_id, staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create table shift_push_subscriptions (
  id bigint generated by default as identity primary key,
  property_id uuid not null references properties(id) on delete restrict,
  staff_profile_id uuid not null,
  endpoint text not null unique check (btrim(endpoint) <> ''),
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (property_id, staff_profile_id)
    references shift_staff_profiles(property_id, id) on delete restrict
);

create index shifts_property_date_idx on shifts(property_id, shift_date);
create index shift_swap_requests_property_status_idx on shift_swap_requests(property_id, status);
create index shift_swap_requests_requester_idx on shift_swap_requests(property_id, requester_staff_profile_id);
create index shift_swap_requests_recipient_idx on shift_swap_requests(property_id, recipient_staff_profile_id);
create index shift_absence_requests_property_status_idx on shift_absence_requests(property_id, status);
create index shift_absence_requests_staff_idx on shift_absence_requests(property_id, staff_profile_id);
create index shift_preassignment_requests_property_status_idx on shift_preassignment_requests(property_id, status);
create index shift_preassignment_requests_staff_idx on shift_preassignment_requests(property_id, staff_profile_id);
create index shift_push_subscriptions_staff_idx on shift_push_subscriptions(property_id, staff_profile_id);

create trigger shift_staff_profiles_set_updated_at before update on shift_staff_profiles
  for each row execute function set_updated_at();
create trigger shifts_set_updated_at before update on shifts
  for each row execute function set_updated_at();
create trigger shift_swap_requests_set_updated_at before update on shift_swap_requests
  for each row execute function set_updated_at();
create trigger shift_absence_requests_set_updated_at before update on shift_absence_requests
  for each row execute function set_updated_at();
create trigger shift_preassignment_requests_set_updated_at before update on shift_preassignment_requests
  for each row execute function set_updated_at();
create trigger shift_month_states_set_updated_at before update on shift_month_states
  for each row execute function set_updated_at();
create trigger shift_settings_set_updated_at before update on shift_settings
  for each row execute function set_updated_at();
create trigger shift_preferences_set_updated_at before update on shift_preferences
  for each row execute function set_updated_at();
create trigger shift_push_subscriptions_set_updated_at before update on shift_push_subscriptions
  for each row execute function set_updated_at();

-- Policies use this helper instead of querying shift_staff_profiles under its
-- own RLS. It only answers whether the current Core profile owns the supplied
-- module staff record; it grants no authority by itself.
create function is_shift_staff_self(p_property_id uuid, p_staff_profile_id uuid)
returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1
    from public.shift_staff_profiles s
    where s.property_id = p_property_id
      and s.id = p_staff_profile_id
      and s.profile_id = (select auth.uid())
      and s.active
      and public.has_permission(p_property_id, 'shifts.view')
  );
$$;

revoke all on function is_shift_staff_self(uuid, uuid) from public, anon;
grant execute on function is_shift_staff_self(uuid, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Grants and RLS
-- ---------------------------------------------------------------------------

alter table shift_staff_profiles enable row level security;
alter table shifts enable row level security;
alter table shift_swap_requests enable row level security;
alter table shift_absence_requests enable row level security;
alter table shift_preassignment_requests enable row level security;
alter table shift_month_states enable row level security;
alter table shift_settings enable row level security;
alter table shift_preferences enable row level security;
alter table shift_read_notifications enable row level security;
alter table shift_push_subscriptions enable row level security;

revoke all on table shift_staff_profiles, shifts, shift_swap_requests,
  shift_absence_requests, shift_preassignment_requests, shift_month_states,
  shift_settings, shift_preferences, shift_read_notifications,
  shift_push_subscriptions from anon;

grant select, insert, update, delete on table shift_staff_profiles, shifts,
  shift_swap_requests, shift_absence_requests, shift_preassignment_requests,
  shift_month_states, shift_settings, shift_preferences,
  shift_read_notifications, shift_push_subscriptions to authenticated;

grant usage, select on sequence shifts_id_seq, shift_swap_requests_id_seq,
  shift_absence_requests_id_seq, shift_preassignment_requests_id_seq,
  shift_push_subscriptions_id_seq to authenticated;

create policy shift_staff_profiles_select on shift_staff_profiles for select to authenticated
  using (has_permission(property_id, 'shifts.view'));
create policy shift_staff_profiles_insert on shift_staff_profiles for insert to authenticated
  with check (has_permission(property_id, 'shifts.manage'));
create policy shift_staff_profiles_update on shift_staff_profiles for update to authenticated
  using (has_permission(property_id, 'shifts.manage'))
  with check (has_permission(property_id, 'shifts.manage'));
create policy shift_staff_profiles_delete on shift_staff_profiles for delete to authenticated
  using (has_permission(property_id, 'shifts.manage'));

create policy shifts_select on shifts for select to authenticated
  using (has_permission(property_id, 'shifts.view'));
create policy shifts_insert on shifts for insert to authenticated
  with check (has_permission(property_id, 'shifts.manage'));
create policy shifts_update on shifts for update to authenticated
  using (has_permission(property_id, 'shifts.manage'))
  with check (has_permission(property_id, 'shifts.manage'));
create policy shifts_delete on shifts for delete to authenticated
  using (has_permission(property_id, 'shifts.manage'));

create policy shift_swap_requests_select on shift_swap_requests for select to authenticated
  using (
    has_permission(property_id, 'shifts.requests.manage')
    or is_shift_staff_self(property_id, requester_staff_profile_id)
    or is_shift_staff_self(property_id, recipient_staff_profile_id)
  );
create policy shift_swap_requests_insert on shift_swap_requests for insert to authenticated
  with check (
    has_permission(property_id, 'shifts.requests.manage')
    or (status = 'pending' and is_shift_staff_self(property_id, requester_staff_profile_id))
  );
create policy shift_swap_requests_update on shift_swap_requests for update to authenticated
  using (has_permission(property_id, 'shifts.requests.manage'))
  with check (has_permission(property_id, 'shifts.requests.manage'));
create policy shift_swap_requests_delete on shift_swap_requests for delete to authenticated
  using (has_permission(property_id, 'shifts.requests.manage'));

create policy shift_absence_requests_select on shift_absence_requests for select to authenticated
  using (
    has_permission(property_id, 'shifts.requests.manage')
    or is_shift_staff_self(property_id, staff_profile_id)
  );
create policy shift_absence_requests_insert on shift_absence_requests for insert to authenticated
  with check (
    has_permission(property_id, 'shifts.requests.manage')
    or (status = 'pending' and is_shift_staff_self(property_id, staff_profile_id))
  );
create policy shift_absence_requests_update on shift_absence_requests for update to authenticated
  using (has_permission(property_id, 'shifts.requests.manage'))
  with check (has_permission(property_id, 'shifts.requests.manage'));
create policy shift_absence_requests_delete on shift_absence_requests for delete to authenticated
  using (has_permission(property_id, 'shifts.requests.manage'));

create policy shift_preassignment_requests_select on shift_preassignment_requests for select to authenticated
  using (
    has_permission(property_id, 'shifts.requests.manage')
    or is_shift_staff_self(property_id, staff_profile_id)
  );
create policy shift_preassignment_requests_insert on shift_preassignment_requests for insert to authenticated
  with check (
    has_permission(property_id, 'shifts.requests.manage')
    or (status = 'pending' and is_shift_staff_self(property_id, staff_profile_id))
  );
create policy shift_preassignment_requests_update on shift_preassignment_requests for update to authenticated
  using (has_permission(property_id, 'shifts.requests.manage'))
  with check (has_permission(property_id, 'shifts.requests.manage'));
create policy shift_preassignment_requests_delete on shift_preassignment_requests for delete to authenticated
  using (has_permission(property_id, 'shifts.requests.manage'));

create policy shift_month_states_select on shift_month_states for select to authenticated
  using (has_permission(property_id, 'shifts.view'));
create policy shift_month_states_insert on shift_month_states for insert to authenticated
  with check (has_permission(property_id, 'shifts.manage'));
create policy shift_month_states_update on shift_month_states for update to authenticated
  using (has_permission(property_id, 'shifts.manage'))
  with check (has_permission(property_id, 'shifts.manage'));
create policy shift_month_states_delete on shift_month_states for delete to authenticated
  using (has_permission(property_id, 'shifts.manage'));

create policy shift_settings_select on shift_settings for select to authenticated
  using (has_permission(property_id, 'shifts.view'));
create policy shift_settings_insert on shift_settings for insert to authenticated
  with check (has_permission(property_id, 'shifts.manage'));
create policy shift_settings_update on shift_settings for update to authenticated
  using (has_permission(property_id, 'shifts.manage'))
  with check (has_permission(property_id, 'shifts.manage'));
create policy shift_settings_delete on shift_settings for delete to authenticated
  using (has_permission(property_id, 'shifts.manage'));

create policy shift_preferences_select on shift_preferences for select to authenticated
  using (has_permission(property_id, 'shifts.view'));
create policy shift_preferences_insert on shift_preferences for insert to authenticated
  with check (
    has_permission(property_id, 'shifts.manage')
    or is_shift_staff_self(property_id, staff_profile_id)
  );
create policy shift_preferences_update on shift_preferences for update to authenticated
  using (
    has_permission(property_id, 'shifts.manage')
    or is_shift_staff_self(property_id, staff_profile_id)
  )
  with check (
    has_permission(property_id, 'shifts.manage')
    or is_shift_staff_self(property_id, staff_profile_id)
  );
create policy shift_preferences_delete on shift_preferences for delete to authenticated
  using (
    has_permission(property_id, 'shifts.manage')
    or is_shift_staff_self(property_id, staff_profile_id)
  );

create policy shift_read_notifications_select on shift_read_notifications for select to authenticated
  using (is_shift_staff_self(property_id, staff_profile_id));
create policy shift_read_notifications_insert on shift_read_notifications for insert to authenticated
  with check (is_shift_staff_self(property_id, staff_profile_id));
create policy shift_read_notifications_update on shift_read_notifications for update to authenticated
  using (is_shift_staff_self(property_id, staff_profile_id))
  with check (is_shift_staff_self(property_id, staff_profile_id));
create policy shift_read_notifications_delete on shift_read_notifications for delete to authenticated
  using (is_shift_staff_self(property_id, staff_profile_id));

create policy shift_push_subscriptions_select on shift_push_subscriptions for select to authenticated
  using (is_shift_staff_self(property_id, staff_profile_id));
create policy shift_push_subscriptions_insert on shift_push_subscriptions for insert to authenticated
  with check (is_shift_staff_self(property_id, staff_profile_id));
create policy shift_push_subscriptions_update on shift_push_subscriptions for update to authenticated
  using (is_shift_staff_self(property_id, staff_profile_id))
  with check (is_shift_staff_self(property_id, staff_profile_id));
create policy shift_push_subscriptions_delete on shift_push_subscriptions for delete to authenticated
  using (is_shift_staff_self(property_id, staff_profile_id));
